# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16QybF79QlLIkxNyvnGtW18HWCs7Ir9j8
"""

#Tugas 1

print('## Nomor1 ##')
def celcius_ke_fahrenheit(celcius):
    fahrenheit= (celcius*9/5)+32
    return fahrenheit

suhu_celcius1 = 0
suhu_celcius2 = 100
suhu_fahrenheit1 = celcius_ke_fahrenheit(suhu_celcius1)

suhu_fahrenheit2 = celcius_ke_fahrenheit(suhu_celcius2)
print(f"suhu_celcius, {suhu_celcius1} sama dengan, {suhu_fahrenheit1}")

#cetak 100 celcius ke 212 fahrenheit
suhu_fahrenheit2 = celcius_ke_fahrenheit (suhu_celcius2)
print(f"suhu celcius, {suhu_celcius2} sama dengan, {suhu_fahrenheit2}")

# Tugas 2

print()
print('## Nomor3 ##')
def genap_ganjil(bilangan):
    hitung = bilangan % 2 == 0 #menentukan bilangan ganjil atau genap
    return hitung #mengembalikan nilai hitung

angka = 4
hasil = genap_ganjil(angka)
print(f"bilangan {angka} bernilai {hasil}")

angka2 = 7
hasil2 = genap_ganjil(angka2)
print(f"bilangan {angka2} bernilai {hasil2}")

# Tugas 3

print()
print('## Nomor3 ##')
def cek_kelulusan(nilai):
    if nilai > 60:
        return 'lulus'
    else:
        return 'gagal'

nilai_yazid = 95
status = cek_kelulusan(nilai_yazid)
print(f"nilai: {nilai_yazid}, status: {status}")

nilai_yazid = 60
status = cek_kelulusan(nilai_yazid)
print(f"nilai: {nilai_yazid}, status: {status}")

# Tugas 4
print()
print('## Nomor 4 ##')
def bilangan_ganjil(bilangan): #nilai = bilangan yang ingin dicari
    return [i for i in range(1,bilangan,2)]
print(bilangan_ganjil(20)) #(20) nilai yang telah dimasukan